[versions]
org-springframework-boot = "3.5.10"

[libraries]
org-springframework-spring-framework-bom = "org.springframework:spring-framework-bom:6.2.15"
org-springframework-security-spring-security-bom = "org.springframework.security:spring-security-bom:6.5.0-SNAPSHOT"
org-springframework-data-spring-data-bom = "org.springframework.data:spring-data-bom:2024.1.13"

[plugins]
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.6" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }
